baseURL = "https://prathwishshetty.netlify.com/"
languageCode = "en-us"
title = "Prathwish Shetty"
theme = "hugo-resume"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    firstName = "Prathwish"
    lastName = "Shetty"
    address = "Boston, MA"
    phone = "1-617-373-0840"
    contactNote = "Data Scientist"
    profileImage = "img/Squirtle.jpg"
    email = "shetty.prat@northeastern.edu"
    description = "Aspiring Data Scientist"
    favicon = "images/favicon.ico"
    search=true
    # what sections
    showSkills = true
    showProjects = true
    showPosts = true
    showPublications = false
    showExperience = true
    showEducation = true

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/prathwishshetty/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/prathwishshetty/"


[params.google.analytics]
    trackerID = "UA-124611753-1"
