baseURL = "https://angry-archimedes-6b9b0f.netlify.com/"
languageCode = "en-us"
title = "Prathwish SHetty"
theme = "hugo-resume"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    firstName = "Prathwish"
    lastName = "Shetty"
    address = "Boston, MA"
    phone = "1-617-373-0840"
    contactNote = "Data Scientist"
    profileImage = "img/TechChat.png"
    email = "shetty.prat@northeastern.com"
    description = "Software Platform Engineer with experience leveraging agile, DevOps, and CI/CD to manage large scale distributed platforms both on prem and in public cloud."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = false
    showExperience = true
    showEducation = true

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/prathwishshetty/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/prathwishshetty/"


[params.google.analytics]
    trackerID = "XX-123446-01"
